"""
Django settings for centrak project.
Generated by 'django-admin startproject' using Django 1.8.15.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
import os
import mongoengine

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_DIR = os.path.abspath(os.path.join(BASE_DIR, '..'))
INST_DIR = os.path.join(ROOT_DIR, 'instance')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-g!@ij9zw4vfk+nso%+blz@9@-=)lwe-+(kt+x=ojlpg6ph(8p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'on') == 'on'
ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # third-party
    'ezaddress',
    'mongoengine',
    'django_filters',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_mongoengine',
    
    # internal
    'main',
    'core',
    'enumeration',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'centrak.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # internal
                'main.context_processors.menu',
                'main.context_processors.jsconf',
                'main.context_processors.current_date',
            ],
        },
    },
]

WSGI_APPLICATION = 'centrak.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(INST_DIR, 'var', 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Lagos'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(ROOT_DIR, 'static')
]


##: ==+: mongo-engine settings
_MONGODB_NAME = 'centrak'
_MONGODB_HOST = ''
_MONGODB_USER = ''
_MONGODB_PWD  = ''

#mongoengine.connect(_MONGODB_NAME)


##: ==+: Auth:
LOGIN_URL = '/account/login'
LOGIN_REDIRECT_URL = '/'


##: ==+: Internal
CENTRAK_OFFICIAL_DOMAINS = ['kedco.ng', 'kedco.net', 'tmp.kedco.ng']
CENTRAK_ADMIN_PREFIX_URL = '/admin/'
CENTRAK_API_ROOT         = '/api/v1/'

CENTRAK_DEFAULT_PAGE_SIZE = 50
CENTRAK_CAPTURE_PAGE_SIZE = 200


from . import local_settings
